### ISSUE TITLE
[Call For Discussion] Shall we set the default value of remove_target_edge_type to False?

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#835]
Originally, we set remove_target_edge_type to True. So in edge prediction tasks (classification and regression) the target edge type is not included in message passing by default. But, is this the right practice?

Related code: https://github.com/awslabs/graphstorm/blob/ea5e5848dd0619ed8205730e11ab389a63212720/python/graphstorm/config/argument.py#L1695-L1709

**Comment by zheng-da** [comment]
if the edge classification is to predict the existence of an edge between two nodes, we should remove the target edge in the message passing to avoid information leak.
if it's to predict some attributes associated with an edge, it may depend on.
since we don't know what to predict, to be safe, we should remove the target edge in message passing by default.

**Comment by classicsong** [comment]
I see what you mean. Make sense.
